/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=preview --include-runtime=false functions/types.d.ts` (hash: 4e9425eb193c6691fb7a539c049a7efe)
interface __BaseEnv_Env {
	NEWSLETTER_DB: D1Database;
	NODE_VERSION: "22.23.2";
	PUBLIC_TURNSTILE_SITE_KEY: "0x4AAAAAADKRCm67kAoc7SHU";
	NEWSLETTER_CONFIRMATION_ORIGIN: "https://codex-resolve-all-audit.integrautomacao-com-br.pages.dev";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
