/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false functions/types.d.ts` (hash: 639fa177e4d7a0d44226f0e9a02b93d9)
interface __BaseEnv_Env {
	NODE_VERSION: "22.12.0";
	PUBLIC_TURNSTILE_SITE_KEY: "0x4AAAAAADKRCm67kAoc7SHU";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
