/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=preview --include-runtime=false functions/types.d.ts` (hash: dfedde540074bef0c82f1bc446c265a7)
interface __BaseEnv_Env {
	NEWSLETTER_DB: D1Database;
	NODE_VERSION: "22.23.2";
	PUBLIC_TURNSTILE_SITE_KEY: "0x4AAAAAADKRCm67kAoc7SHU";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
