blank_issues_enabled: false
contact_links:
  - name: Falar com a Integra
    url: https://integrautomacao.com/contato/
    about: Para contatos comerciais ou dúvidas técnicas, use o formulário do site.
